### ISSUE TITLE
Mi Band 2

### ISSUE THREAD

**Issue by marceloaraujo** [betomaluje/Mi-Band#11]
Hello everyone,
I would like to build an app for Mi Band 2, with notifications of the apps on the mi band screen, also with features presents in this lib. but I didn't found an api for that. How this lib works on Mi Band 2?

**Comment by luispereira** [comment]
I would glad to help reverse engineering mid band 2 to make an sdk for it, if is not yet existent

**Comment by marceloaraujo** [comment]
Alright. I understand. Thanks for answer.
