### ISSUE TITLE
Custom vibration doesnt' work - Protocol problem?

### ISSUE THREAD

**Issue by DarioNevistic** [betomaluje/Mi-Band#9]
Does anyone know how can I implement custom vibration? There are some protocol changes there, but I can't find what they are. 
I changed service from fee0 to 1802 and other vibrations are working now, but there is another problem with service and protocol with custom vibration.

Anyone know how to fix that?

**Comment by andenq** [comment]
Trying to fix this too, though I'm trying to fix it on pangliangs library. Doesn't matter though as I'm sending the commands that I find here. I know of apps in the store that succesfully implement custom vibrations, so they should work!

Have you made any progress since opening this issue?

**Comment by mcdaryo** [comment]
Can you please share how you trigger the vibration-until-stop? 
From Elad Nava, this helped on original MiBand- Color Led:

public synchronized void notifyBandRepeated(final int flashColour, final int vibrateTimes, final int waitDuration) {
        List<BLEAction> list = new ArrayList<>();

        byte[] colors = convertRgb(flashColour);

        for (int i = 1; i <= vibrateTimes; i++) {
            list.add(new WriteAction(Profile.UUID_SERVICE_VIBRATE, Profile.UUID_CHAR_ALERT_LEVEL, Protocol.VIBRATION_NEW_FIRMWARE));
            list.add(new WriteAction(Profile.UUID_CHAR_CONTROL_POINT, colors));
            list.add(new WaitAction(waitDuration));
        }

        queue(list);
    }

**Comment by andenq** [comment]
I'm currently much deeper inside the libraries, but the following is what I'm sending to my band:

Service: Profile.UUID_SERVICE_VIBRATE
Characteristic: Profile.UUID_CHAR_ALERT_LEVEL, 
Data: new byte[] { 2 }

It makes my band with heart sensor (1S?) vibrate until I tap it (or almost, it keeps going for like a few seconds). For some reason betamalujes library (this) has ```byte[] VIBRATION_UNTIL_CALL_STOP = {0x8, 1};``` which does not work for me. Maybe try changing this to what I used?
